= Trabalho 2, Entrega 1

== Definição do Time

* Alex Peral
* Fabio Leal
* Felipe Fonseca
* Paulo Jerônimo
* Renan Filgueiras
* Sigfredo Rocha

== Briefing do projeto

Atualmente muito se tem falado sobre a corrupção no governo brasileiro, uma parte da população começou a acompanhar, cobrar e fiscalizar na medida do possível o uso do dinheiro público. Um dos grandes problemas é a dificuldade de controle sobre as compras do governo pois a quantidade de contratos é enorme, para um cidadão conferir se o valor pago pelo governo aos fornecedores está de acordo com o mercado, ou seja, não estão jogando seu dinheiro fora, ele precisa buscar manualmente esses dados, o que dificilmente trará resultado satisfatório. A solução proposta é a criação de um programa que recupera dos dados abertos do governo as informações de compras e minerar os valores dos produtos na web para apresentar de forma mais informativa e inteligente uma análise.

== Personas: 
* Militantes virtuais (redes sociais)
* Empresários (interessados em licitações)
* Vem p/ rua (Militantes que vão para a rua efetivamente)
* Testemunhas (de atos de corrupção)

== Solução:
O sistema contará com um cadastro (com a opção do anonimato), um formulário para registrar uma história com tags para facilitar buscas e uma listagem de histórias já relatadas com busca e filtro, para pesquisa por estado, órgão, etc.
O sistema deve possuir um mecanismo de retorno às pessoas que postaram suas reclamações. Se for anônimo os resultados serão apenas apresentados no histórico do sistema.
Outra funcionalidade será o mapa da corrupção que apresentará os focos de corrupções e a localização das empresas que ganharam licitações a fim da população verificar a autenticidade de cada uma, descobrindo assim possíveis empresas fantasmas.
As soluções descritas acima serão refinadas e talvez modificadas de acordo com os resultados de validação da ideia, por meio de protótipo e entrevista aberta.

== Validação da proposta:
* Protótipo da ideia
* Entrevista aberta
  - Possíveis questões: Você já presenciou algum fato que considera corrupção? Se sim, onde foi e como foi? Você sentiu vontade de realizar alguma denúncia ou expor isso? E sabe como levar essa denúncia a entidades responsáveis? 

== Plano de entregas semanais

* 24-06-2016 - Definição de personas, reformulação do plano de entregas
* 01-07-2016 - Definição da solução, validação com o usuário
* 08-07-2016 - Protótipo
* 15-07-2016 - Finalizar a validação do protótipo e fazer a entrega final

== Atividades do projeto

* https://trello.com/b/oSCeJeya/projeto-de-combate-a-corrupcao
